version: "3.8"

services:
  db:
    image: mysql:5.7
    environment:
      MYSQL_ROOT_PASSWORD: root_password
      MYSQL_DATABASE: db_name
      MYSQL_USER: username
      MYSQL_PASSWORD: password
    ports:
      - "3306:3306"
    volumes:
      - db_data:/var/lib/mysql
      - ./sql/setup_database.sql:/docker-entrypoint-initdb.d/setup_database.sql

  web:
    build: .
    command: /scripts/start.sh
    environment:
      FLASK_ENV: development
      DATABASE_URL: mysql://username:password@db/db_name
    ports:
      - "5000:5000"
    depends_on:
      - db
    volumes:
      - .:/app

  locust:
    build: .
    command: locust -f tests/load_tests/locustfile.py --host=http://web:5000
    ports:
      - "8089:8089"
    environment:
      API_TYPE: REST
    depends_on:
      - web
    volumes:
      - .:/app

volumes:
  db_data:
